run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

issues:
  exclude-dirs:
    - vendor
    - .github

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck

    # Exclude known linters from partially hard-vendored code
    - path: pkg/ui/dgraph/
      linters:
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0
