{{- if and .Values.basicAuth.enabled .Values.basicAuth.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "lookout.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lookout.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.basicAuth.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.basicAuth.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "lookout.fullname" . }}-basic-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        .htpasswd: "{{ `{{ .htpasswd }}` }}"
  data:
    - secretKey: htpasswd
      remoteRef:
        key: {{ .Values.basicAuth.externalSecret.remoteKey }}
        property: {{ .Values.basicAuth.externalSecret.property | default "htpasswd" }}
{{- end }}
